# Generated by Django 2.1.5 on 2020-10-21 18:10

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='car',
            fields=[
                ('id', models.AutoField(help_text='Unique ID for this particular car', primary_key=True, serialize=False)),
                ('mark', models.CharField(max_length=254)),
                ('model', models.CharField(max_length=254)),
                ('city', models.CharField(max_length=254)),
                ('county', models.CharField(max_length=254)),
                ('location', models.CharField(max_length=254)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='carDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('radio', models.BooleanField(default=False)),
                ('display', models.BooleanField(default=False)),
                ('airConditioner', models.BooleanField(default=False)),
                ('glassFogging', models.BooleanField(default=False)),
                ('inside', models.CharField(default='dummy text', max_length=255)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('lights', models.BooleanField(default=False)),
                ('colour', models.CharField(default='ffffff', max_length=6)),
                ('car', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='signup.car')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.BooleanField(default=False)),
                ('email_confirmed', models.BooleanField(default=False)),
                ('companySpec', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(3), django.core.validators.MinValueValidator(1)])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='userPreferences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('humidity', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('temperature', models.DecimalField(decimal_places=2, default=25, max_digits=10)),
                ('displayStartPage', models.CharField(default='google.com', max_length=254)),
                ('radioWave', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tvChannel', models.IntegerField(blank=True, null=True)),
                ('frigeTemperature', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
