# Generated by Django 2.1.5 on 2020-10-20 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreferences',
            name='displayStartPage',
            field=models.CharField(default='google.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='frigeTemperature',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='humidity',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='radioWave',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='temperature',
            field=models.DecimalField(decimal_places=2, default=25, max_digits=10),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='tvChannel',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
