# Generated by Django 2.1.5 on 2020-10-21 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0002_auto_20201021_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='id',
            field=models.AutoField(help_text='Unique ID for this particular car', primary_key=True, serialize=False),
        ),
    ]
