# Generated by Django 2.1.5 on 2020-10-21 11:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0002_auto_20201020_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='companySpec',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(3), django.core.validators.MinValueValidator(1)]),
        ),
    ]
