# Generated by Django 2.1.5 on 2020-10-21 11:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('signup', '0003_profile_companyspec'),
    ]

    operations = [
        migrations.CreateModel(
            name='carRent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular car', primary_key=True, serialize=False)),
                ('mark', models.CharField(max_length=254)),
                ('model', models.CharField(max_length=254)),
                ('city', models.CharField(max_length=254)),
                ('county', models.CharField(max_length=254)),
                ('location', models.CharField(max_length=254)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
