# Generated by Django 2.1.5 on 2020-10-21 11:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('signup', '0004_carrent'),
    ]

    operations = [
        migrations.CreateModel(
            name='car',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular car', primary_key=True, serialize=False)),
                ('mark', models.CharField(max_length=254)),
                ('model', models.CharField(max_length=254)),
                ('city', models.CharField(max_length=254)),
                ('county', models.CharField(max_length=254)),
                ('location', models.CharField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='cars',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='carrent',
            name='user',
        ),
        migrations.DeleteModel(
            name='carRent',
        ),
        migrations.AddField(
            model_name='car',
            name='cars',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='signup.cars'),
        ),
    ]
