# Generated by Django 2.1.5 on 2020-10-21 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0005_auto_20201021_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='cars',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='signup.cars'),
        ),
    ]
