# Generated by Django 2.1.5 on 2020-10-21 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0006_auto_20201021_1302'),
    ]

    operations = [
        migrations.CreateModel(
            name='carDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('radio', models.BooleanField(default=False)),
                ('display', models.BooleanField(default=False)),
                ('airConditioner', models.BooleanField(default=False)),
                ('glassFogging', models.BooleanField(default=False)),
                ('inside', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('lights', models.BooleanField(default=False)),
                ('colour', models.CharField(max_length=6)),
                ('car', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='signup.car')),
            ],
        ),
    ]
