# Generated by Django 2.1.5 on 2020-10-21 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0007_cardetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardetails',
            name='colour',
            field=models.CharField(default='ffffff', max_length=6),
        ),
        migrations.AlterField(
            model_name='cardetails',
            name='inside',
            field=models.CharField(default='dummy text', max_length=255),
        ),
        migrations.AlterField(
            model_name='cardetails',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
